version: '3'

services:
  db:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
  
  api:
    build: .
    ports:
      - "5300:80"
    depends_on:
      - db
    environment:
      - MONGO_CONNECTION=mongodb://db:27017/profiles
      - ASPNETCORE_ENVIRONMENT=Development
    
  profiles:
    image: sekir0/profiles_api:latest
    ports:
      - "5400:80"
    depends_on:
      - db
    environment:
      - MONGO_CONNECTION=mongodb://db:27017/profiles