version: '3'

services:
  api:
    build: .
    ports:
      - "5500:80"
    environment:
      - MONGO_CONNECTION=mongodb://db:27017/profiles
      - ASPNETCORE_ENVIRONMENT=Development
  db:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
  
  rabbit:
    image: rabbitmq:3.9.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"